CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260922194435_InitialPostgres') THEN
    CREATE EXTENSION IF NOT EXISTS btree_gist;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260922194435_InitialPostgres') THEN
    CREATE TABLE "AuditEvents" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ActorId" text NOT NULL,
        "Action" character varying(80) NOT NULL,
        "TargetId" text NOT NULL,
        "OccurredAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_AuditEvents" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260922194435_InitialPostgres') THEN
    CREATE TABLE "Doctors" (
        "Id" character varying(64) NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Specialty" character varying(200) NOT NULL,
        "BookingMethod" text NOT NULL,
        "Funding" text NOT NULL,
        "IsService" boolean NOT NULL,
        "RequiresConfirmation" boolean NOT NULL,
        "StaffOnly" boolean NOT NULL,
        "TuesdayFirst" boolean NOT NULL,
        "DurationMinutes" integer NOT NULL,
        "DemoScheduleEdited" boolean NOT NULL,
        "ScheduleVersion" integer NOT NULL DEFAULT 1,
        CONSTRAINT "PK_Doctors" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Doctor_Duration" CHECK ("DurationMinutes" BETWEEN 10 AND 120 AND "DurationMinutes" % 5 = 0)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260922194435_InitialPostgres') THEN
    CREATE TABLE "Patients" (
        "Id" character varying(64) NOT NULL,
        "Name" character varying(80) NOT NULL,
        "Email" character varying(120) NOT NULL,
        "Phone" character varying(30) NOT NULL,
        "IsDemonstration" boolean NOT NULL,
        CONSTRAINT "PK_Patients" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260922194435_InitialPostgres') THEN
    CREATE TABLE "Settings" (
        "Key" text NOT NULL,
        "Value" text NOT NULL,
        CONSTRAINT "PK_Settings" PRIMARY KEY ("Key")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260922194435_InitialPostgres') THEN
    CREATE TABLE "AvailabilityExceptions" (
        "Id" text NOT NULL,
        "DoctorId" character varying(64) NOT NULL,
        "Date" date NOT NULL,
        "Start" time without time zone NOT NULL,
        "End" time without time zone NOT NULL,
        "IsAvailable" boolean NOT NULL,
        "Reason" character varying(120) NOT NULL,
        CONSTRAINT "PK_AvailabilityExceptions" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Exception_Range" CHECK ("Start" < "End"),
        CONSTRAINT "FK_AvailabilityExceptions_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260922194435_InitialPostgres') THEN
    CREATE TABLE "SourceSchedules" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Row" integer NOT NULL,
        "Days" text NOT NULL,
        "Start" text NOT NULL,
        "End" text NOT NULL,
        "Type" text NOT NULL,
        "Note" text NOT NULL,
        "DoctorId" character varying(64) NOT NULL,
        CONSTRAINT "PK_SourceSchedules" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SourceSchedules_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260922194435_InitialPostgres') THEN
    CREATE TABLE "WorkingPeriods" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Day" integer NOT NULL,
        "Start" time without time zone NOT NULL,
        "End" time without time zone NOT NULL,
        "DoctorId" character varying(64) NOT NULL,
        CONSTRAINT "PK_WorkingPeriods" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_WorkingPeriod_Range" CHECK ("Start" < "End" AND "Day" BETWEEN 0 AND 6),
        CONSTRAINT "FK_WorkingPeriods_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260922194435_InitialPostgres') THEN
    CREATE TABLE "Accounts" (
        "Id" text NOT NULL,
        "Email" character varying(120) NOT NULL,
        "NormalizedEmail" character varying(120) NOT NULL,
        "Name" character varying(80) NOT NULL,
        "PasswordHash" text NOT NULL,
        "Role" character varying(20) NOT NULL,
        "DoctorId" character varying(64),
        "PatientId" character varying(64),
        "Enabled" boolean NOT NULL,
        "IsDemo" boolean NOT NULL,
        "FailedAttempts" integer NOT NULL,
        "LockedUntil" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Accounts" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Account_RoleLink" CHECK (("Role" = 'Patient' AND "PatientId" IS NOT NULL AND "DoctorId" IS NULL) OR ("Role" = 'Doctor' AND "DoctorId" IS NOT NULL AND "PatientId" IS NULL) OR ("Role" = 'Administrator' AND "DoctorId" IS NULL AND "PatientId" IS NULL)),
        CONSTRAINT "FK_Accounts_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Accounts_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260922194435_InitialPostgres') THEN
    CREATE TABLE "Appointments" (
        "Id" character varying(64) NOT NULL,
        "DoctorId" character varying(64) NOT NULL,
        "PatientId" character varying(64) NOT NULL,
        "Start" timestamp with time zone NOT NULL,
        "End" timestamp with time zone NOT NULL,
        "Status" character varying(20) NOT NULL,
        "Version" integer NOT NULL,
        "CreatedBy" text NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "RequestId" text NOT NULL,
        CONSTRAINT "PK_Appointments" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Appointment_Range" CHECK ("Start" < "End"),
        CONSTRAINT "CK_Appointment_Status" CHECK ("Status" IN ('Scheduled','Confirmed','Completed','Cancelled','NoShow')),
        CONSTRAINT "CK_Appointment_Version" CHECK ("Version" > 0),
        CONSTRAINT "FK_Appointments_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Appointments_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260922194435_InitialPostgres') THEN
    CREATE TABLE "IdempotencyRequests" (
        "AccountId" text NOT NULL,
        "RequestId" text NOT NULL,
        "Fingerprint" character varying(64) NOT NULL,
        "ResponseJson" jsonb NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_IdempotencyRequests" PRIMARY KEY ("AccountId", "RequestId"),
        CONSTRAINT "FK_IdempotencyRequests_Accounts_AccountId" FOREIGN KEY ("AccountId") REFERENCES "Accounts" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260922194435_InitialPostgres') THEN
    CREATE TABLE "Sessions" (
        "TokenHash" character varying(64) NOT NULL,
        "AccountId" text NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "IsDemo" boolean NOT NULL,
        CONSTRAINT "PK_Sessions" PRIMARY KEY ("TokenHash"),
        CONSTRAINT "FK_Sessions_Accounts_AccountId" FOREIGN KEY ("AccountId") REFERENCES "Accounts" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260922194435_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_Accounts_DoctorId" ON "Accounts" ("DoctorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260922194435_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_Accounts_NormalizedEmail" ON "Accounts" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260922194435_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_Accounts_PatientId" ON "Accounts" ("PatientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260922194435_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_Appointments_CreatedBy_RequestId" ON "Appointments" ("CreatedBy", "RequestId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260922194435_InitialPostgres') THEN
    CREATE INDEX "IX_Appointments_DoctorId_Start" ON "Appointments" ("DoctorId", "Start");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260922194435_InitialPostgres') THEN
    CREATE INDEX "IX_Appointments_PatientId_Start" ON "Appointments" ("PatientId", "Start");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260922194435_InitialPostgres') THEN
    CREATE INDEX "IX_AuditEvents_OccurredAt" ON "AuditEvents" ("OccurredAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260922194435_InitialPostgres') THEN
    CREATE INDEX "IX_AvailabilityExceptions_DoctorId_Date" ON "AvailabilityExceptions" ("DoctorId", "Date");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260922194435_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_Patients_Email" ON "Patients" ("Email") WHERE "Email" <> '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260922194435_InitialPostgres') THEN
    CREATE INDEX "IX_Sessions_AccountId" ON "Sessions" ("AccountId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260922194435_InitialPostgres') THEN
    CREATE INDEX "IX_Sessions_ExpiresAt" ON "Sessions" ("ExpiresAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260922194435_InitialPostgres') THEN
    CREATE INDEX "IX_SourceSchedules_DoctorId" ON "SourceSchedules" ("DoctorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260922194435_InitialPostgres') THEN
    CREATE INDEX "IX_WorkingPeriods_DoctorId_Day" ON "WorkingPeriods" ("DoctorId", "Day");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260922194435_InitialPostgres') THEN
    ALTER TABLE "Appointments" ADD CONSTRAINT "EX_Appointments_Doctor"
    EXCLUDE USING gist ("DoctorId" WITH =, tstzrange("Start", "End", '[)') WITH &&)
    WHERE ("Status" <> 'Cancelled');
    ALTER TABLE "Appointments" ADD CONSTRAINT "EX_Appointments_Patient"
    EXCLUDE USING gist ("PatientId" WITH =, tstzrange("Start", "End", '[)') WITH &&)
    WHERE ("Status" <> 'Cancelled');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260922194435_InitialPostgres') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260922194435_InitialPostgres', '10.0.12');
    END IF;
END $EF$;
COMMIT;
