<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../Appointments.Core/Appointments.Core.csproj" />
    <ProjectReference Include="../Appointments.Contracts/Appointments.Contracts.csproj" />
    <Content Update="Seed/doctors.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
